<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin.proto

namespace Google\Protobuf\Compiler;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The version number of protocol compiler.
 *
 * Generated from protobuf message <code>google.protobuf.compiler.Version</code>
 */
class Version extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 major = 1;</code>
     */
    protected $major = null;
    /**
     * Generated from protobuf field <code>optional int32 minor = 2;</code>
     */
    protected $minor = null;
    /**
     * Generated from protobuf field <code>optional int32 patch = 3;</code>
     */
    protected $patch = null;
    /**
     * A suffix for alpha, beta or rc release, e.g., "alpha-1", "rc2". It should
     * be empty for mainline stable releases.
     *
     * Generated from protobuf field <code>optional string suffix = 4;</code>
     */
    protected $suffix = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $major
     *     @type int $minor
     *     @type int $patch
     *     @type string $suffix
     *           A suffix for alpha, beta or rc release, e.g., "alpha-1", "rc2". It should
     *           be empty for mainline stable releases.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Plugin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 major = 1;</code>
     * @return int
     */
    public function getMajor()
    {
        return isset($this->major) ? $this->major : 0;
    }

    public function hasMajor()
    {
        return isset($this->major);
    }

    public function clearMajor()
    {
        unset($this->major);
    }

    /**
     * Generated from protobuf field <code>optional int32 major = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMajor($var)
    {
        GPBUtil::checkInt32($var);
        $this->major = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 minor = 2;</code>
     * @return int
     */
    public function getMinor()
    {
        return isset($this->minor) ? $this->minor : 0;
    }

    public function hasMinor()
    {
        return isset($this->minor);
    }

    public function clearMinor()
    {
        unset($this->minor);
    }

    /**
     * Generated from protobuf field <code>optional int32 minor = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMinor($var)
    {
        GPBUtil::checkInt32($var);
        $this->minor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 patch = 3;</code>
     * @return int
     */
    public function getPatch()
    {
        return isset($this->patch) ? $this->patch : 0;
    }

    public function hasPatch()
    {
        return isset($this->patch);
    }

    public function clearPatch()
    {
        unset($this->patch);
    }

    /**
     * Generated from protobuf field <code>optional int32 patch = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPatch($var)
    {
        GPBUtil::checkInt32($var);
        $this->patch = $var;

        return $this;
    }

    /**
     * A suffix for alpha, beta or rc release, e.g., "alpha-1", "rc2". It should
     * be empty for mainline stable releases.
     *
     * Generated from protobuf field <code>optional string suffix = 4;</code>
     * @return string
     */
    public function getSuffix()
    {
        return isset($this->suffix) ? $this->suffix : '';
    }

    public function hasSuffix()
    {
        return isset($this->suffix);
    }

    public function clearSuffix()
    {
        unset($this->suffix);
    }

    /**
     * A suffix for alpha, beta or rc release, e.g., "alpha-1", "rc2". It should
     * be empty for mainline stable releases.
     *
     * Generated from protobuf field <code>optional string suffix = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSuffix($var)
    {
        GPBUtil::checkString($var, True);
        $this->suffix = $var;

        return $this;
    }

}

